// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewProject.Server.Data;

#nullable disable

namespace NewProject.Server.Migrations
{
    [DbContext(typeof(NewProjectServerContext))]
    partial class NewProjectServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewProject.Shared.Customer", b =>
                {
                    b.Property<string>("Phone_Number")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Customer_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Customer_Id")
                        .HasColumnType("int");

                    b.Property<string>("Customer_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Phone_Number");

                    b.ToTable("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
